# Generated by Django 5.1.1 on 2026-06-28 15:41

import django.core.validators
import django.db.models.deletion
import json
import uuid
import wagtail.fields
from django.db import migrations, models


def add_reviews_block(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT page_ptr_id, content FROM pages_homepage")
        rows = cursor.fetchall()

    for page_id, raw_content in rows:
        try:
            content = json.loads(raw_content or "[]")
        except (TypeError, ValueError):
            continue

        if any(block.get("type") == "reviews" for block in content):
            continue

        reviews_block = {
            "type": "reviews",
            "value": {
                "anchor_id": "reviews",
                "heading": "Отзывы",
                "button_text": "Оставить отзыв",
            },
            "id": str(uuid.uuid4()),
        }

        insert_at = next(
            (index for index, block in enumerate(content) if block.get("type") == "feedback"),
            len(content),
        )
        content.insert(insert_at, reviews_block)
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "UPDATE pages_homepage SET content = %s WHERE page_ptr_id = %s",
                [json.dumps(content, ensure_ascii=False), page_id],
            )


def remove_reviews_block(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT page_ptr_id, content FROM pages_homepage")
        rows = cursor.fetchall()

    for page_id, raw_content in rows:
        try:
            content = json.loads(raw_content or "[]")
        except (TypeError, ValueError):
            continue
        filtered = [block for block in content if block.get("type") != "reviews"]
        if len(filtered) != len(content):
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(
                    "UPDATE pages_homepage SET content = %s WHERE page_ptr_id = %s",
                    [json.dumps(filtered, ensure_ascii=False), page_id],
                )


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_homepage_content'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('author_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('review_text', models.TextField(max_length=1200, verbose_name='Текст отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('firstblock', 7), ('about_text_photo', 11), ('work_areas', 20), ('consultation_steps', 26), ('professional_training', 31), ('faq', 37), ('reviews', 41), ('video_player', 50), ('education', 55), ('diplomas', 59), ('prices', 67), ('feedback', 70)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: hero, about — используется в меню навигации', 'label': 'ID раздела (якорь)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок (имя и профессия)'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок (услуги)', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Ссылка кнопки', 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('anchor_id', 0), ('heading', 1), ('subheading', 2), ('description', 3), ('button_text', 4), ('button_link', 5), ('image', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: about-intro — используется в меню навигации', 'label': 'ID раздела (якорь)', 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'label': 'Заголовок', 'required': False}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Текст', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('anchor_id', 8), ('heading', 9), ('text', 10), ('image', 6)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: work-areas — используется в меню навигации', 'label': 'ID раздела (якорь)', 'required': False}), 13: ('wagtail.blocks.RichTextBlock', (), {'label': 'Заголовок раздела', 'required': False}), 14: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Вводный текст', 'required': False}), 15: ('wagtail.blocks.RichTextBlock', (), {'label': 'Название направления', 'required': False}), 16: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ul', 'ol'], 'label': 'Описание', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('heading', 15), ('description', 16)]], {'label': 'Направление'}), 18: ('wagtail.blocks.ListBlock', (17,), {'label': 'Направления работы'}), 19: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ul', 'ol'], 'label': 'С чем не работаю', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('anchor_id', 12), ('heading', 13), ('description', 14), ('areas', 18), ('exclusions', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: consultation-steps — используется в меню навигации', 'label': 'ID раздела (якорь)', 'required': False}), 22: ('wagtail.blocks.RichTextBlock', (), {'label': 'Название шага', 'required': False}), 23: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Описание', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('heading', 22), ('description', 23)]], {'label': 'Шаг'}), 25: ('wagtail.blocks.ListBlock', (24,), {'label': 'Шаги консультации'}), 26: ('wagtail.blocks.StructBlock', [[('anchor_id', 21), ('heading', 13), ('description', 14), ('steps', 25)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: professional-training — используется в меню навигации', 'label': 'ID раздела (якорь)', 'required': False}), 28: ('wagtail.blocks.RichTextBlock', (), {'label': 'Название', 'required': False}), 29: ('wagtail.blocks.StructBlock', [[('heading', 28), ('description', 23)]], {'label': 'Пункт подготовки'}), 30: ('wagtail.blocks.ListBlock', (29,), {'label': 'Пункты подготовки'}), 31: ('wagtail.blocks.StructBlock', [[('anchor_id', 27), ('heading', 13), ('description', 14), ('items', 30)]], {}), 32: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: faq — используется в меню навигации', 'label': 'ID раздела (якорь)', 'required': False}), 33: ('wagtail.blocks.RichTextBlock', (), {'label': 'Вопрос', 'required': False}), 34: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'label': 'Ответ', 'required': False}), 35: ('wagtail.blocks.StructBlock', [[('question', 33), ('answer', 34)]], {'label': 'Вопрос-ответ'}), 36: ('wagtail.blocks.ListBlock', (35,), {'label': 'FAQ'}), 37: ('wagtail.blocks.StructBlock', [[('anchor_id', 32), ('heading', 13), ('description', 14), ('items', 36)]], {}), 38: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: reviews — используется в меню навигации', 'label': 'ID раздела (якорь)', 'required': False}), 39: ('wagtail.blocks.CharBlock', (), {'default': 'Отзывы', 'label': 'Заголовок'}), 40: ('wagtail.blocks.CharBlock', (), {'default': 'Оставить отзыв', 'label': 'Текст кнопки'}), 41: ('wagtail.blocks.StructBlock', [[('anchor_id', 38), ('heading', 39), ('button_text', 40)]], {}), 42: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: video, practice — используется в меню навигации', 'label': 'ID раздела (якорь)', 'required': False}), 43: ('wagtail.blocks.CharBlock', (), {'label': 'Надзаголовок', 'required': False}), 44: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок блока'}), 45: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Загрузите mp4/mov/webm как документ, чтобы файл хранился на сервере', 'label': 'Видео-файл', 'required': False}), 46: ('wagtail.blocks.CharBlock', (), {'help_text': 'Запасной вариант: /media/videos/session.mp4 или https://example.com/video.mp4', 'label': 'Ссылка на видео', 'required': False}), 47: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Постер', 'required': False}), 48: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: 12 минут', 'label': 'Подпись длительности', 'required': False}), 49: ('wagtail.blocks.CharBlock', (), {'help_text': 'Короткий акцент рядом с видеоплеером', 'label': 'Подпись под видео', 'required': False}), 50: ('wagtail.blocks.StructBlock', [[('anchor_id', 42), ('eyebrow', 43), ('heading', 44), ('description', 3), ('video_file', 45), ('video_url', 46), ('poster', 47), ('duration_label', 48), ('note', 49)]], {}), 51: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: education — используется в меню навигации', 'label': 'ID раздела (якорь)', 'required': False}), 52: ('wagtail.blocks.RichTextBlock', (), {'label': 'Содержимое', 'required': False}), 53: ('wagtail.blocks.StructBlock', [[('heading', 9), ('contents', 52)]], {}), 54: ('wagtail.blocks.ListBlock', (53,), {}), 55: ('wagtail.blocks.StructBlock', [[('anchor_id', 51), ('heading', 13), ('education_items', 54)]], {}), 56: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок раздела', 'required': False}), 57: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 58: ('wagtail.blocks.ListBlock', (57,), {'label': 'Дипломы'}), 59: ('wagtail.blocks.StructBlock', [[('anchor_id', 51), ('heading', 56), ('diplomas', 58)]], {}), 60: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: prices — используется в меню навигации', 'label': 'ID раздела (якорь)', 'required': False}), 61: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'label': 'Заголовок раздела'}), 62: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'label': 'Название тарифа'}), 63: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'label': 'Цена'}), 64: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Например: длительность 1 час', 'label': 'Дополнительный текст', 'required': False}), 65: ('wagtail.blocks.StructBlock', [[('name', 62), ('price', 63), ('extra_text', 64), ('description', 16)]], {'label': 'Тариф'}), 66: ('wagtail.blocks.ListBlock', (65,), {'label': 'Тарифы'}), 67: ('wagtail.blocks.StructBlock', [[('anchor_id', 60), ('heading', 61), ('tariffs', 66)]], {}), 68: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: feedback, contact — используется в меню навигации', 'label': 'ID раздела (якорь)', 'required': False}), 69: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 70: ('wagtail.blocks.StructBlock', [[('anchor_id', 68), ('heading', 69)]], {})}),
        ),
        migrations.RunPython(add_reviews_block, remove_reviews_block),
    ]
